FROM alpine:3.7
MAINTAINER Mohammad Abdoli Rad <m.abdolirad@gmail.com>

LABEL org.label-schema.name="alpine" \
        org.label-schema.vendor="Dockage" \
        org.label-schema.description="Alpine image that forms the base for Dockage's docker images." \
        org.label-schema.vcs-url="https://github.com/dockage/alpine" \
        org.label-schema.version="3.7" \
        org.label-schema.license="MIT"

RUN apk add --no-cache su-exec ca-certificates nano tar curl findutils