---
kind: pipeline
name: alpine3.5

steps:
  - name: alpine3.5
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/alpine
      dockerfile: 3.5/Dockerfile
      tags:
        - '3.5'

  - name: alpine3.5-openrc
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/alpine
      dockerfile: 3.5/openrc/Dockerfile
      tags:
        - '3.5-openrc'

---
kind: pipeline
name: alpine3.6

steps:
  - name: alpine3.6
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/alpine
      dockerfile: 3.6/Dockerfile
      tags:
        - '3.6'

  - name: alpine3.6-openrc
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/alpine
      dockerfile: 3.6/openrc/Dockerfile
      tags:
        - '3.6-openrc'

---
kind: pipeline
name: alpine3.7

steps:
  - name: alpine3.7
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/alpine
      dockerfile: 3.7/Dockerfile
      tags:
        - '3.7'

  - name: alpine3.7-openrc
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/alpine
      dockerfile: 3.7/openrc/Dockerfile
      tags:
        - '3.7-openrc'

---
kind: pipeline
name: alpine3.8

steps:
  - name: alpine3.8
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/alpine
      dockerfile: 3.8/Dockerfile
      tags:
        - '3.8'

  - name: alpine3.8-openrc
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/alpine
      dockerfile: 3.8/openrc/Dockerfile
      tags:
        - '3.8-openrc'

---
kind: pipeline
name: alpine3.9

steps:
  - name: alpine3.9
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/alpine
      dockerfile: 3.9/Dockerfile
      tags:
        - '3.9'

  - name: alpine3.9-openrc
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/alpine
      dockerfile: 3.9/openrc/Dockerfile
      tags:
        - '3.9-openrc'

---
kind: pipeline
name: alpine3.10

steps:
  - name: alpine3.10
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/alpine
      dockerfile: 3.10/Dockerfile
      tags:
        - '3.10'

  - name: alpine3.10-openrc
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/alpine
      dockerfile: 3.10/openrc/Dockerfile
      tags:
        - '3.10-openrc'

kind: pipeline
name: alpine3.11

steps:
  - name: alpine3.11
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/alpine
      dockerfile: 3.11/Dockerfile
      tags:
        - '3.11'
        - 'latest'

  - name: alpine3.11-openrc
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/alpine
      dockerfile: 3.11/openrc/Dockerfile
      tags:
        - '3.11-openrc'

---
kind: pipeline
name: notify

steps:
  - name: microbadger
    image: plugins/webhook
    settings:
      urls:
        - https://hooks.microbadger.com/images/dockage/alpine/NQPdqhP-XDsT2pay1t3-AK-nI1k=

depends_on:
  - alpine3.5
  - alpine3.6
  - alpine3.7
  - alpine3.8
  - alpine3.9
